# Random Numbers

### Random Module

In [1]:
import random

In [2]:
a = random.random() # random float in range 0 to 1
print(a)

0.18874443862432033


In [6]:
a = random.uniform(1,10) # specified range
print(a) # random float number in range 1 to 10

4.013615129594893


In [7]:
a = random.randint(1,10) # specified range
print(a) # random int numebr in range 1 to 10 (including 10)

10


In [10]:
a = random.randrange(1,20) # specified range
print(a) # random int number in range 1 to 10 (not including 20)

7


In [16]:
a = random.normalvariate(0, 1) # 1st argument is called mu and 2nd argument is called sigma
# useful while working with statistics
print(a) # it wil pick a random value from a normal disribution (check for it in the internet)

0.2473962131483968


In [22]:
mylist = list('ABCDEFGH')
print(mylist) # each character is different elemnt in our list
a = random.choice(mylist)
print(a) # it will pick a random element from our list

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
B


In [23]:
mylist = list('ABCDEFGH')
a = random.sample(mylist, 3) # 3 - number of different elements we want to pick
print(a) # it will pick 3 random, unique element from our list

['E', 'F', 'G']


In [35]:
mylist = list('ABCDEFGH')
a = random.choices(mylist, k=3)
print(a) # it picks 3 random elements from our list but they can be the same

['C', 'C', 'D']


In [39]:
mylist = list('ABCDEFGH')
random.shuffle(mylist) # it shuffle a list randomly in place
print(mylist)

['G', 'D', 'A', 'C', 'B', 'H', 'F', 'E']


In [42]:
random.seed(1)
print(random.random())
print(random.randint(1,10))
# it produces the same set of random values
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2


In [43]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.13436424411240122
2
0.9560342718892494
1


### Secrets Module

In [45]:
import secrets

In [46]:
a = secrets.randbelow(10) # random int number in range 10 (but not including 10)
print(a)

0


In [48]:
a = secrets.randbits(4) # it generate a radnom int number with k(4) random bits
print(a) # it generate a random number in range 0-15 because max 4 bit numer is 1111 = 2^3+2^2+2^1+2^0=15

7


In [50]:
mylist=list('ABCDEFGH')
a = secrets.choice(mylist) # it will pick a random choice that is not reproducable
print(a)

D


### Numpy module

In [51]:
import numpy as np

In [53]:
# array with random floats
a = np.random.rand(3) # 3 - dimension
print(a) # it will produce 1D array with 3 elements in it

[0.07546226 0.523668   0.0375983 ]


In [55]:
a = np.random.rand(3,3)
print(a) # 3 by 3 array

[[0.47083663 0.87132984 0.18956511]
 [0.90589488 0.67294667 0.0853758 ]
 [0.18061244 0.31799538 0.25151373]]


In [58]:
a = np.random.randint(0,10, 3) # 0,10 is range and 3 is size - 1D array
print(a) # random int number in range 0 to 10 (not including 10)

[3 7 2]


In [62]:
a = np.random.randint(0,10, (3,4)) # to gebnerate array with different dimension i have to use a tuple
print(a) # 3 by 4 array with random int numbers

[[4 5 6 5]
 [2 7 9 1]
 [1 2 2 5]]


In [66]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
np.random.shuffle(array) # it only shuffle elements in the first access (rows)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [69]:
# numpy random generator uses a different number generator than the standard library random
# numpy has also different seed than the seed from a standard library
# while working with numpy arrays you should use np.random.seed instead of random.seed from a standarrd library
# np.random.seed and random.seed from a standard library are completely different seed generators
np.random.seed(1)
print(np.random.rand(3,3)) # 3 by 3 dimension
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
